import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

import { AppSidebar } from '@/components/app-sidebar';
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar';
import { Providers } from '@/components/provider';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <Providers>
                    <SidebarProvider
                        style={
                            {
                                '--sidebar-width': '13rem',
                            } as React.CSSProperties
                        }
                    >
                        <AppSidebar />
                        <SidebarInset>
                            <div className="flex flex-1 flex-col ">{children}</div>
                        </SidebarInset>
                    </SidebarProvider>
                </Providers>
            </body>
        </html>
    );
}
